routes/web.php
<?php

use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'ArticlesController@home')->name('articles.home');
Route::resource('/articles', 'ArticlesController');
Route::get('/articles/category/{id}', 'ArticlesController@category')->name('articles.category');

Route::resource('/articles/{article}/comments', 'Articles\ArticleCommentController', [
    'names' => [
        'index' => 'articles.comments.index'
    ]
]);

Route::resource('/comments', 'Comments\CommentController');
Route::resource('/comments/{comment}/replies', 'Comments\CommentReplyController');

Route::resource('/categories', 'CategoriesController');

Route::get('/home', 'HomeController@index')->name('home');

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\MorphMany;

/**
 * Class Article
 *
 * @package App
 *
 * @author Alexander Schilling
 */
class Article extends Material
{

    /** @var string[] Allowed fields */
    protected $fillable = [
        'category_id',
        'title',
        'slug',
        'thumbnail',
        'content',
        'status_id',
        'hits',
        'allow_comments',
        'meta_title',
        'meta_description',
    ];

    /**
     * Get the route key for the model.
     *
     * @return string
     */
    public function getRouteKeyName(): string
    {
        return 'slug';
    }

    /**
     * @return BelongsTo
     */
    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class)->where('material_id', self::MATERIAL_ARTICLE_ID);
    }

    /**
     * @return MorphMany
     */
    public function comments(): MorphMany
    {
        return $this->morphMany(Comment::class, 'commentable')->whereNull('parent_id')->latest();
    }

    /**
     * @return int
     */
    public function allCommentsCount(): int
    {
        return $this->morphMany(Comment::class, 'commentable')->count();
    }
}

app/Http/Controllers/Articles/ArticleCommentController.php
<?php

namespace App\Http\Controllers\Articles;

use App\Article;
use App\Http\Controllers\Controller;
use App\Http\Requests\CommentRequest;
use App\Http\Resources\CommentResource;
use Illuminate\Http\Resources\Json\AnonymousResourceCollection;

/**
 * Class ArticleCommentController
 *
 * @package App\Http\Controllers\Articles
 *
 * @author Alexander Schilling
 */
class ArticleCommentController extends Controller
{
    /**
     * Index
     *
     * @param Article $article
     *
     * @return AnonymousResourceCollection
     */
    public function index(Article $article): AnonymousResourceCollection
    {
        return CommentResource::collection(
            $article->comments()->with(['children', 'user'])->paginate(config('articles.comments_per_page'))
        );
    }

    /**
     * Store a comment
     *
     * @param Article $article
     * @param CommentRequest $commentRequest
     *
     * @return CommentResource
     */
    public function store(Article $article, CommentRequest $commentRequest): CommentResource
    {
        $comment = $article->comments()->make($commentRequest->validated());

        $commentRequest->user()->comments()->save($comment);

        return new CommentResource($comment);
    }
}

app/Http/Controllers/ArticlesController.php
<?php

namespace App\Http\Controllers;

use App\Article;
use App\Category;
use App\Material;
use App\Http\Requests\ArticleRequest;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

/**
 * Class ArticlesController
 *
 * @package App\Http\Controllers
 *
 * @author Alexander Schilling
 */
class ArticlesController extends Controller
{
    /**
     * ArticlesController constructor.
     */
    public function __construct()
    {
        /**
         * @see ArticlePolicy
         */
        $this->authorizeResource(Article::class);
    }

    /**
     * Display a listing of the articles for admin.
     *
     * @return View
     */
    public function index(): View
    {
        $articles = Article::orderBy('created_at', 'desc')
            ->paginate(config('articles.admin_per_page'));

        return view('articles.index')->with('articles', $articles);
    }

    /**
     * Display a listing of the articles.
     *
     * @return View
     */
    public function home(): View
    {
        $articles = Article::where('status_id', Material::STATUS_PUBLIC)
            ->latest()
            ->paginate(config('articles.per_page'));

        return view('articles.home')->with('articles', $articles);
    }

    /**
     * Display the article from specified category.
     *
     * @param Article $article
     *
     * @return View
     */
    public function category($slug): View
    {
        $category = Category::where('material_id', Material::MATERIAL_ARTICLE_ID)->where('slug', $slug)->firstOrFail();

        $articles = Article::where('status_id', Material::STATUS_PUBLIC)
            ->where('category_id', $category->id)
            ->latest()
            ->paginate(config('articles.category_per_page'));

        return view('articles.category')->withArticles($articles)->withCategory($category);
    }

    /**
     * Show the form for creating a new article.
     *
     * @param Article $article
     *
     * @return View
     */
    public function create(Article $article): View
    {
        $categories = Category::where('material_id', Material::MATERIAL_ARTICLE_ID)->get();
        return view('articles.create')->with(['article' => $article, 'categories' => $categories]);
    }

    /**
     * Store a newly created article in storage.
     *
     * @param ArticleRequest $articleRequest
     *
     * @return RedirectResponse
     */
    public function store(ArticleRequest $articleRequest): RedirectResponse
    {
        Article::create($articleRequest->validated());

        return redirect()->back()->with('message', __('articles.message_article_added'));
    }

    /**
     * Display the specified article.
     *
     * @param Article $article
     *
     * @return View
     */
    public function show(Article $article): View
    {
        return view('articles.show')->with('article', $article);
    }

    /**
     * Show the form for editing the specified article.
     *
     * @param Article $article
     *
     * @return View
     */
    public function edit(Article $article): View
    {
        $categories = Category::where('material_id', Material::MATERIAL_ARTICLE_ID)->get();
        return view('articles.edit')->with(['article' => $article, 'categories' => $categories]);
    }

    /**
     * Update the specified article in storage.
     *
     * @param ArticleRequest $articleRequest
     * @param Article $article
     *
     * @return RedirectResponse
     */
    public function update(ArticleRequest $articleRequest, Article $article): RedirectResponse
    {
        $article->update($articleRequest->validated());
        return redirect()->back()->with('message', __('articles.message_article_saved'));
    }

    /**
     * Remove the specified article from storage.
     *
     * @param Article $article
     *
     * @return RedirectResponse
     */
    public function destroy(Article $article): RedirectResponse
    {
        $article->delete();
        return redirect()->route('articles.index');
    }
}

resources/views/articles/category.blade.php
@extends('layouts.app')

@section('title', $category->name)

@section('content')

    <div id="articles_category">

        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <h1 class="text-white">
                    <i class="fas fa-folder px-2"></i>
                    {{ $category->name }}
                </h1>
            </div>
        </div>

        @include('articles.partials.articles-list')

    </div>

@endsection

resources/views/articles/create.blade.php
@extends('layouts.app')

@section('title', __('articles.create_headline'))

@section('content')

    <div id="articles_create">

        <h1 class="text-white pb-3">
            @lang('articles.create_headline')
        </h1>

        <div class="bg-white px-3 pt-3 pb-1 rounded-lg">

            @include('partials.message')

            <form method="POST" action="{{ route('articles.store') }}">
                @include('articles.form')
            </form>

        </div>

    </div>

@endsection

resources/views/articles/edit.blade.php
@extends('layouts.app')

@section('title', __('articles.edit_headline'))

@section('content')

    <div id="articles_edit">

        <h1 class="text-white pb-3">
            @lang('articles.edit_headline')
        </h1>

        <div class="bg-white px-3 pt-3 pb-1 rounded-lg">

            @include('partials.message')

            <form method="post" action="{{ route('articles.update', ['article' => $article->slug]) }}">

                @method('PATCH')
                @csrf

                @include('articles.form')

            </form>

            <form method="post" action="{{ route('articles.destroy', ['article' => $article->slug]) }}">

                @method('DELETE')
                @csrf

                <div class="form-group">
                    <button type="submit" class="btn btn-danger btn-submit">@lang('articles.button_delete')</button>
                </div>

            </form>

        </div>

    </div>

@endsection

resources/views/articles/form.blade.php
@csrf

<div class="row">
    <div class="col">
        <div class="form-group">
            <label for="category_id">@lang('articles.form_label_category')</label>
            <select class="form-control" name="category_id" id="category_id">
                @foreach ($categories as $category)
                    <option value="{{ $category->id }}" {{ ( $category->id == old('category_id', $article->category_id ?? null)) ? 'selected' : '' }}>
                        {{ $category->name }}
                    </option>
                @endforeach
            </select>
            @error('category_id')
            <div class="text-danger">{{ $message }}</div>
            @enderror
        </div>
    </div>
    <div class="col">
        <div class="form-group">
            <label for="status_id">@lang('articles.form_label_status')</label>
            <select class="form-control" name="status_id" id="status_id">
                @foreach ($article::getStatus() as $key => $value)
                    <option value="{{ $key }}" {{ ( $key == old('status_id', $article->status_id ?? null)) ? 'selected' : '' }}>
                        {{ $value }}
                    </option>
                @endforeach
            </select>
            @error('status_id')
            <div class="text-danger">{{ $message }}</div>
            @enderror
        </div>
    </div>
    <div class="col">
        <div class="form-group">
            <label for="slug">@lang('articles.form_label_slug')</label>
            <input type="text" name="slug" class="form-control @error('slug') is-invalid @enderror" id="slug" value="{{ old('slug', $article->slug ?? null) }}">
            @error('slug')
            <div class="text-danger">{{ $message }}</div>
            @enderror
        </div>
    </div>
    <div class="col">
        <div class="form-group">
            <label for="thumbnail">@lang('articles.form_label_thumbnail')</label>
            <input type="text" name="thumbnail" class="form-control @error('thumbnail') is-invalid @enderror" id="thumbnail" value="{{ old('thumbnail', $article->thumbnail ?? null) }}">
            @error('thumbnail')
            <div class="text-danger">{{ $message }}</div>
            @enderror
        </div>
    </div>
</div>

<div class="form-group">
    <label for="title">@lang('articles.form_label_title')</label>
    <input type="text" name="title" class="form-control @error('title') is-invalid @enderror" id="title" value="{{ old('title', $article->title ?? null) }}">
    @error('title')
    <div class="text-danger">{{ $message }}</div>
    @enderror
</div>

<div class="form-group">
    <label for="content">@lang('articles.form_label_content')</label>
    <textarea name="content" class="form-control @error('content') is-invalid @enderror" id="content">{{ old('content', $article->content ?? null) }}</textarea>
    @error('content')
    <div class="text-danger">{{ $message }}</div>
    @enderror
</div>

<div class="row">
    <div class="col">
        <div class="form-group">
            <label for="meta_title">@lang('articles.form_label_meta_title')</label>
            <input type="text" name="meta_title" class="form-control @error('meta_title') is-invalid @enderror" id="meta_title" value="{{ old('meta_title', $article->meta_title ?? null) }}">
            @error('meta_title')
            <div class="text-danger">{{ $message }}</div>
            @enderror
        </div>
    </div>
    <div class="col">
        <div class="form-group">
            <label for="meta_description">@lang('articles.form_label_meta_description')</label>
            <input type="text" name="meta_description" class="form-control @error('meta_description') is-invalid @enderror" id="meta_description" value="{{ old('meta_description', $article->meta_description ?? null) }}">
            @error('meta_description')
            <div class="text-danger">{{ $message }}</div>
            @enderror
        </div>
    </div>
</div>

<div class="form-group">
    <div class="form-check">
        <input type="hidden" name="allow_comments" value="0">
        <input class="form-check-input" type="checkbox" name="allow_comments" id="allow_comments" {{ old('allow_comments', $article->allow_comments ?? null) ? 'checked' : '' }} value="1">
        <label class="form-check-label" for="allow_comments">@lang('articles.form_label_allow_comments')</label>
    </div>
    @error('allow_comments')
    <div class="text-danger">{{ $message }}</div>
    @enderror
</div>

<div class="form-group">
    <button type="submit" class="btn btn-success btn-submit">@lang('articles.button_submit')</button>
</div>

resources/views/articles/home.blade.php
@extends('layouts.app')

@section('title', __('articles.home_headline'))

@section('content')

    <div id="articles_home">

        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <h1 class="text-white">
                    <i class="fas fa-feather px-2"></i>
                    @lang('articles.home_headline')
                </h1>
            </div>
        </div>

        @include('articles.partials.articles-list')

    </div>

@endsection

resources/views/articles/index.blade.php
@extends('layouts.app')

@section('title', __('articles.index_headline'))

@section('content')

    <div id="articles_index">

        <div class="row">

            <div class="col-md-10">
                <h1 class="text-white">@lang('articles.index_headline')</h1>
            </div>

            <div class="col-md-2">
                <a href="{{ route('articles.create') }}" class="btn btn-lg btn-block btn-primary btn-h1-spacing">
                    <i class="fas fa-plus-square"></i> @lang('articles.button_create')
                </a>
            </div>

            <div class="col-md-12">
                <hr>
            </div>

        </div>

        <div class="row bg-white pt-3 rounded-lg">

            <div class="col-md-12">

                @if($articles->count() > 0)

                    <table class="table table-striped table-bordered">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>@lang('articles.thead_title')</th>
                            <th>@lang('articles.thead_status')</th>
                            <th>@lang('articles.thead_hits')</th>
                            <th>@lang('articles.thead_comments')</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($articles as $article)
                            <tr>
                                <td>{{ $article->id }}</td>
                                <td>{{ $article->title }}</td>
                                <td>{{ \App\Material::getStatus()[$article->status_id] }}</td>
                                <td>{{ $article->hits }}</td>
                                <td>{{ $article->allCommentsCount() ?? 0 }}</td>
                                <td>
                                    <a href="{{ route('articles.show', ['article' => $article->slug]) }}">
                                        <i class="far fa-eye"></i>
                                    </a>
                                    <a href="{{ route('articles.edit', ['article' => $article->slug]) }}">
                                        <i class="far fa-edit"></i>
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>

                    {{ $articles->links() }}

                @else

                    <div class="row">
                        <div class="col-md-8 col-md-offset-2">
                            <div class="pb-3">
                                @lang('articles.empty_text')
                            </div>
                        </div>
                    </div>

                @endif

            </div>

        </div>

    </div>

@endsection

resources/views/articles/show.blade.php
@extends('layouts.app')

@section('title', $article->title)

@section('meta_title', $article->meta_title)
@section('meta_description', $article->meta_description)

@section('content')

    <div id="articles_show">

        <div class="row">

            <div class="col-md-10">
                <h1 class="text-white">
                    {{$article->title}}
                </h1>
            </div>

            @can('update', $article)
                <div class="col-md-2">
                    <a href="{{ route('articles.edit', ['article' => $article->slug]) }}" class="btn btn-lg btn-block btn-primary btn-h1-spacing">
                        <i class="far fa-edit"></i> @lang('articles.button_edit')
                    </a>
                </div>
            @endauth

            <div class="col-md-9 py-3 px-2">

                @if (isset($article->thumbnail))
                    <div><img src="{{ $article->thumbnail }}" alt="" class="img-thumbnail bg-white mb-3"></div>
                @endif

                @if($article->status_id === \App\Material::STATUS_DRAFT)
                    <div>
                        @lang('articles.status_draft')
                    </div>
                @endif

                <div class="bg-white py-3 px-4 rounded-lg">

                    <div>
                        {!! \App\Helpers\Text::hideCut(\App\Helpers\Markdown::process($article->content)) !!}
                    </div>

                    <div class="d-flex justify-content-end">
                        <div class="px-2">
                            <i class="far fa-clock"></i>
                            <span class="px-1">
                                {{$article->created_at->format(\App\Material::DATE_FORMAT)}}
                            </span>
                        </div>
                        @if ($article->hits > 0)
                            <div class="px-2">
                                <i class="far fa-eye"></i>
                                <span class="px-1">
                                    {{$article->hits}}
                                </span>
                            </div>
                        @endif
                        @if ($article->category)
                            <div class="px-2">
                                <i class="far fa-folder"></i>
                                <span class="px-1">
                                    <a href="{{ route('articles.category', ['id' => $article->category->slug]) }}">
                                        {{$article->category->name}}
                                    </a>
                                </span>
                            </div>
                        @endif
                    </div>

                </div>

                @if ($article->allow_comments)
                    <div class="px-2 py-3">
                        <h3 class="py-1 text-white">@lang('articles.comments')</h3>
                        <comments endpoint="{{ route('articles.comments.index', $article) }}"></comments>
                    </div>
                @endif

            </div>

            <div class="col-md-3 py-3 px-2">
                <div class="card">
                    <div class="card-header">
                        Widget header
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">Widget Title</h5>
                        <p class="card-text">Widget content</p>
                        <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>
            </div>

        </div>

    </div>

@endsection